version: "3.8"

services:
  kafka-1:
    image: bitnami/kafka:latest
    user: 'root'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=tF0HTgFQTO-xH1eBLFOpLg
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://${HOSTNAME-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - my-network
    volumes:
      - /home/djarallah/work/kafka-formations/apache-kafka-server/docker/volumes/server-1:/bitnami/kafka

  # kafka-2:
  #   image: bitnami/kafka:latest
  #   user: 'root'
  #   ports:
  #     - "9094:9094"
  #     - "9090:9090"
  #   environment:
  #     - KAFKA_CFG_NODE_ID=2
  #     - KAFKA_KRAFT_CLUSTER_ID=tF0HTgFQTO-xH1eBLFOpLg
  #     - KAFKA_CFG_PROCESS_ROLES=controller,broker
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://${HOSTNAME}:9094
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  #   networks:
  #     - my-network
  #   volumes:
  #     - /home/djarallah/work/kafka-formations/apache-kafka-server/docker/volumes/server-2:/bitnami/kafka

  consumer-1:
    image: djarallahbrahim/job-offer-consumer-ws:main
    user: 'root'
    ports:
      - 8089:8089
    environment:
      - SPRING_APPLICATION_NAME=joboffer consumer
      - SERVER_PORT=8089
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9094
      - SPRING_KAFKA_CONSUMER_GROUP_ID=job-offer-created-events
      - SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES=*
      - TOPIC_KAFKA_NAME=job-offer-events-topic
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/job_application
      - SPRING_DATASOURCE_USERNAME=samtyga
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=senderjoboffer@gmail.com
      - SPRING_MAIL_PASSWORD=ylyo yslg gbqq yhdg
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - logging.level.org.apache.kafka=DEBUG
      - logging.level.org.springframework.kafka=DEBUG
    networks:
      - my-network
    depends_on:
      - mysql
      - kafka-1
  producer-1:
    image: djarallahbrahim/job-offer-producer-ws:main
    user: 'root'
    ports:
      - 8098:8080
    environment:
      - SPRING_APPLICATION_NAME=kafka-ws
      - SERVER_PORT=8080
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9094
      - SPRING_KAFKA_PRODUCER_KEY_SERIALIZER=org.apache.kafka.common.serialization.StringSerializer
      - SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER=org.springframework.kafka.support.serializer.JsonSerializer
      - SPRING_KAFKA_PRODUCER_ENABLE_IDEMPOTENCE=true
      - SPRING_KAFKA_PRODUCER_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION=5
      - SPRING_KAFKA_PRODUCER_ACKS=all
      - SPRING_KAFKA_PRODUCER_PROPERTIES_LINGER_MS=0
      - SPRING_KAFKA_PRODUCER_PROPERTIES_REQUEST_TIMEOUT_MS=30000
      - SPRING_KAFKA_PRODUCER_PROPERTIES_DELIVERY_TIMEOUT_MS=120000
      - TOPIC_KAFKA_NAME=job-offer-events-topic
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/job_application
      - SPRING_DATASOURCE_USERNAME=samtyga
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - logging.level.org.apache.kafka=DEBUG
      - logging.level.org.springframework.kafka=DEBUG
    networks:
      - my-network
    depends_on:
      - mysql
      - kafka-1
  #     - kafka-2

  mysql:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=job_application
      - MYSQL_USER=samtyga
      - MYSQL_PASSWORD=root
    networks:
      - my-network
    ports:
      - "3306:3306"
networks:
  my-network:
    driver: bridge